### ISSUE TITLE
All tests are using the same amounts of messages/rules and don't test large rule sets.

### ISSUE THREAD

**Issue by whoozle** [hola/challenge_mail_filter#1]
I just tried to fix my implementation to pass the correctness tests and I noticed that you does not test large rule sets. All tests were run at 100k×100 configuration. I believe this does not check scalability of the algorithm design at all. Many fast implementation will fail if you make rule set large enough. This is unfortunate, because I was trying to remove polynomial dependency of rules number in the first place. 
Frankly, I thought the scalability was the goal of challenge.

**Comment by whoozle** [comment]
If you generate rule set large enough, 

```
var messages = fill_obj(100, generate_message);
var rules = fill(10000, generate_rule);
```

it gives you:

```
Pass #4: 259ms
Pass #5: 266ms
Pass #6: 713ms
Pass #7: 726ms
```

for Denis Kreshikhin (his solution is _really_ brilliant and clearly should be the winner)

And 

```
Pass #4: 180ms
Pass #5: 180ms
Pass #6: 182ms
Pass #7: 183ms
```

for my implementation. :)

**Comment by xderry** [comment]
Thanks for your feedback. We are re-checking the results, and will update soon.

http://hola.org/dna#truth-mistakes

**Comment by AgentRX** [comment]
@xderry, I agree with this issue.
The best way, for example is to generate 3 different data/filter amounts with 3 different random generated datas.

**Comment by feldgendler** [comment]
Scalability for the number of rules is not the goal. In the scenario presented in the problem statement, the ruleset is a single user's set of mail filters. This typically doesn't grow with the mail archive size, and 100 rules should be enough even for a sophisticated user. The number of messages, however, is where we expect scalability.

**Comment by whoozle** [comment]
you might come up with better excuse. ;)

**Comment by feldgendler** [comment]
This is what I sincerely think. I don't expect a real-life mail filtering engine to be optimized for thousands of rules (lots of messages, yes, but not lots of rules). Sure, I expect it to _support_ lots of rules, but I won't be surprised if my real-life e-mail program becomes seriously slow with thousdands of filtering rules. This is not a sane use case.

**Comment by feldgendler** [comment]
100 rules is already more than most users have ever tried to configure.

**Comment by cakeinpanic** [comment]
@feldgendler but isn't surprise a goal of such challenges? you don't expect it working fast, but it works and you stand up and exclaim 'heureka!" and new algorithm is developed, tadaam

**Comment by whoozle** [comment]
Honestly, I would not bother me with any 'real world' task if I knew that before. You mention neither any limits nor this task is actually real. 

The challenge means 'making impossible possible', whatever it might be: playing music on calculator, 10Kb rogue like rpg in browser, 8-bit 3D shooter or processing 10^6 rules on 10^8 messages in a second. These "challenges" limited with imaginary farfetched things are not fun at all, really.

**Comment by AgentRX** [comment]
@cakeinpanic I beleive organizers mean their specific problem and test filters using the problem's conditions.

Make JS filter for this common task is not good idea. JS is too slow language for bulk processing. So it means they want to create browser-oriented solution.

I hope next time they will tell us more problem specification.

**Comment by feldgendler** [comment]
@whoozle: In response to many questions, I said that the performance test input will resemble real life. The goal was to optimize your code to real-life inputs and achieve the best performance.

However, as @AgentRX points out, we should avoid situations when the optimization target is unclear (how many rules? how many messages?) because some participants might get a different idea of what they should optimize for, and be disappointed when the tests are eventually published.
