### ISSUE TITLE
Some decisions do not pass my tests correctly

### ISSUE THREAD

**Issue by zbitname** [hola/challenge_mail_filter#6]
https://github.com/hola/challenge_mail_filter/pull/5
Please check it and merge my pull request.

**Comment by anthrax63** [comment]
+1

**Comment by anthrax63** [comment]
Correctness tests should cover more variants of messages and patterns. I ran my correctness tests with all of the submissions and many filters didn't pass it. It is important, because if filter fills actions lower than expected, it may seriously affect on the execution time.

**Comment by prostoandrei** [comment]
+1

**Comment by pkolt** [comment]
+1

**Comment by AgentRX** [comment]
+2

**Comment by AgentRX** [comment]
+1

**Comment by feldgendler** [comment]
Your contribution is incorporated into the test system. Thank you!
